/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/contracts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getContract"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analysis/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAnalysis"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getLeaderboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["compare"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        DetectorName: "global-static-write" | "write-in-loop" | "read-modify-write" | "duplicate-read";
        /** @description A static storage key: resolved segments, or [] for a dynamic key. */
        StaticKey: {
            segments: string[];
        };
        DetectorFinding: {
            detector: string;
            function: string | null;
            key: string | null;
            message: string;
        };
        FunctionAccess: {
            function_name: string;
            storage_reads: components["schemas"]["StaticKey"][];
            storage_writes: components["schemas"]["StaticKey"][];
        };
        AnalysisReport: {
            source_name: string;
            functions: components["schemas"]["FunctionAccess"][];
            detectors: components["schemas"]["DetectorFinding"][];
        };
        LedgerAccount: {
            account_id: string;
        };
        LedgerTrustLine: {
            account_id: string;
            asset: string;
        };
        LedgerContractData: {
            contract_id: string;
            key: string;
        };
        LedgerContractCode: {
            contract_id: string;
        };
        LedgerContractTtl: {
            contract_id: string;
        };
        /** @description A ledger key as an externally-tagged enum. Unknown variants fall through to a raw record. */
        LedgerKey: {
            Account: components["schemas"]["LedgerAccount"];
        } | {
            TrustLine: components["schemas"]["LedgerTrustLine"];
        } | {
            ContractData: components["schemas"]["LedgerContractData"];
        } | {
            ContractCode: components["schemas"]["LedgerContractCode"];
        } | {
            ContractTtl: components["schemas"]["LedgerContractTtl"];
        } | {
            Other: string;
        };
        HotKey: {
            key: components["schemas"]["LedgerKey"];
            reads: number;
            writes: number;
            touch_count: number;
        };
        Cluster: {
            txns: number[];
        };
        Schedule: {
            stages: components["schemas"]["Cluster"][];
        };
        ProfileReport: {
            source: string;
            transaction_count: number;
            distinct_keys: number;
            stage_count: number;
            parallelism: number;
            critical_path_length: number;
            weighted_critical_path_weight: number;
            total_conflicts: number;
            hot_keys: components["schemas"]["HotKey"][];
            schedule: components["schemas"]["Schedule"];
        };
        Grade: {
            score: number;
            letter: string;
        };
        Contract: {
            id: string;
            name: string;
            address: string | null;
            grade: components["schemas"]["Grade"] | null;
            analysis: components["schemas"]["AnalysisReport"] | null;
            profile: components["schemas"]["ProfileReport"] | null;
        };
        LeaderboardEntry: {
            contractId: string;
            name: string;
            score: number;
            parallelism: number;
            rank: number;
        };
        ComparisonSummary: {
            detector_findings_delta: number;
            storage_reads_delta: number;
            storage_writes_delta: number;
        };
        ComparisonFunctionDelta: {
            function_name: string;
            detector_findings_delta: number;
            storage_reads_delta: number;
            storage_writes_delta: number;
        };
        Comparison: {
            leftId: string;
            rightId: string;
            summary: components["schemas"]["ComparisonSummary"];
            functions: components["schemas"]["ComparisonFunctionDelta"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getContract: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A contract with its grade and, when available, analysis and profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Contract"];
                };
            };
        };
    };
    getAnalysis: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Static analysis report for a contract. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisReport"];
                };
            };
        };
    };
    getLeaderboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Contracts ranked by contention score. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaderboardEntry"][];
                };
            };
        };
    };
    compare: {
        parameters: {
            query: {
                left: string;
                right: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Summary and per-function deltas between two contracts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comparison"];
                };
            };
        };
    };
}
